### ISSUE TITLE
add back BM histograms booking in default mode in SL

### ISSUE THREAD

**Issue by acarvalh** [HEP-KBFI/hh-bbww#17]
description on title

**Comment by ktht** [comment]
The only difference I could find wrt DL analysis is in DL code itself:
https://github.com/HEP-KBFI/hh-bbww/blob/1234dd89d528fccf66f167d58d43f53851951cff/bin/analyze_hh_bb2l.cc#L2336-L2346
It seems redundant because the BM names are constructed in `HHWeightInterface_2`. Need to test that removing those lines won't break anything.

**Comment by ktht** [comment]
The code shown in my previous post was indeed redundant, as it apparently created multiple cycles of the same histogram:
![Screenshot_20201020_222721](https://user-images.githubusercontent.com/6233872/96634985-f29b9e00-1323-11eb-87c9-79e2384f20e6.png)
There's only once such histogram after the fix.
