### ISSUE TITLE
Make LBN work with CMSSW

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-bbww#20]
The problem is that embedded Python doesn't quite work when loading tensorflow, and the problem appears to be coming from tensorflow itself. Thus, the only realistic options that could work for us are:
1. make the evaluation of the LBN model work during the runtime:
    i. create a Python script that reads the LBN model and listens to stdin;
    ii. spawn the script from the analysis;
    iii. in the event loop of the analysis, pass necessary arguments to the script (using the PID or some other handle returned from the previous point) which evaluates the model for a given event;
    iv. make sure to clean up the auxiliary process once the program dies.
2. evaluate the LBN model using nanoAOD-tools and embed the results in the Ntuples;

In the first solution, we would have to spawn the script in a separate process because we want to construct the input model only once per analysis job. Constructing the model for every selected event is prohibitive due to timing constraints.

The second option is disfavored because it requires new (or modifying the existing) software that manages Ntuples and jobs outside CMSSW environment. It also adds another step between Ntuple production and analysis, and requires more human time because of additional Ntuple management.

**Comment by ktht** [comment]
I decided to spend some time on investigating the error and found that linking against `tensorflow-cc`,
```xml
<use name="tensorflow-cc"/>
```
in `BuildFile.xml`, conflicts with importing the tensorflow module from embedded Python code. If I remove this linkage, the code works perfectly. Unfortunately, this dependency comes from core ttH framework, which uses `PhysicsTools/TensorFlow` package of CMSSW, so just dropping this dependency is not possible. There's [this thread](http://cern.ch/go/b9CX) on github describing a similar problem.

**Comment by veelken** [comment]
Hi Karl,

this is very good progress! 

I think we have 4 options now:
1) convert the TensorFlowInterface to evaluating the multi-class DNN for the ttH analysis in python, drop the dependency on the tensorflow-cc library, and evaluate the LBN in python (with the XGBInterface-like approach)
2) convert lbn.py to C++ with one of Xandra's conversion methods and install a newer TensorFlow version in our CMSSW_11_2_x area. I recall that you mentioned this installation is not possible, due to dependency issues, but I don't recall discussing what these dependencies are. I am pretty confident that we can install TensorFlow 2.3 together with CMSSW_11_2_x as an external library, unless CMSSW_11_2_x and TensorFlow themselves have mutually exclusive dependencies, e.g. python 2.7 vs python 3. 
3) convert lbn.py to C++ code and call the C++ API of TensorFlow in the HH->bbWW analysis (I need to admit that I don't know if/how it is possible to use custom NN models with the TensorFlow C++ API, but I think it is worth checking)
4) as a last resort, we can evaluate the LBN when producing Ntuples, but this will be very painful in my opinion, and hence constitutes only the last resort in my opinion

Let's discuss on Monday.

**Comment by ktht** [comment]
As pointed out in bbww chat, the model should be saved as pb as described in [this documentation](https://cms-ml.github.io/documentation/inference/tensorflow2.html). Loading the model can be done purely in C++.
I've implemented the example in [`lbn_example`](https://github.com/HEP-KBFI/hh-bbww/tree/lbn_example) branch. The code that loads and evaluates the model in C++ is at [`bin/test_lbn.cc`](https://github.com/HEP-KBFI/hh-bbww/blob/lbn_example/bin/test_lbn.cc); the training script (which is based on [this notebook](https://gitlab.cern.ch/cms-hh-bbww/cms-hh-to-bbww/-/blob/master/methods/lbn/root_to_lbn.ipynb)) is at [`test/lbn/run_training.py`](https://github.com/HEP-KBFI/hh-bbww/blob/lbn_example/test/lbn/run_training.py); python testing script (based on [this script](https://gitlab.cern.ch/cms-hh-bbww/ml-models/-/blob/master/examples/dnn/pb/test.py)) is at [`test/lbn/test_training.py`](https://github.com/HEP-KBFI/hh-bbww/blob/lbn_example/test/lbn/test_training.py). The next step is to put the C++ code into a class in this repository. (There's no need to modify anything in ttH repository.)

I'm not entirely convinced that we can evaluate models that are produced in TF version that is more recent compared to the TF that comes with CMSSW. Or, at least testing [`these examples`](https://gitlab.cern.ch/cms-hh-bbww/ml-models/-/tree/master/examples/dnn) gave me the impression that TF is not forward-compatible.
