### ISSUE TITLE
Status flag of LHE particles missing

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-bbww#29]
For historical reasons, not all NanoAOD Ntuples have the `LHEPart_status` branch. Initially (and officially), the NanoAOD FW saves only the status = 1 particles to the Ntuple. At some point I modified our CMSSW fork such that it also saves the status flag of the LHE particles to the Ntuple because some of the LHE Higgses had status = 2. All Ntuples that are produced since this change have the branch, but the Ntuples produced before don't. See https://github.com/HEP-KBFI/tth-htt/issues/99#issuecomment-561642001 for more context.

This in turn brings us to the root cause, that `HHGenKinematicsHistManager` uses these LHE particles to compute di-Higgs mass and cos(theta*) variables. This is completely redundant because we already have these variables pre-computed in [post-production](https://github.com/HEP-KBFI/tth-nanoAOD-tools/blob/master/python/postprocessing/modules/diHiggsVarProducer.py) and read at the analysis level (`EventInfo::gen_mHH` and `EventInfo::gen_cosThetaStar`).

**Comment by veelken** [comment]
Hi Karl,

I implemented the reading of LHE particles, in order to compare the gen_mHH and gen_cosThetaStar distributions for NLO vs LO HH samples. The issue was/is that the access via EventInfo works only for the LO samples (the corresponding branches are missing for the NLO samples). Are the HH->bbWW analysis jobs crashing for some samples when they try to read the LHE particles ?

**Comment by ktht** [comment]
Ah now I see the problem: the Ntuple post-production FW is instructed to compute the mHH and cos(theta*) only for the LO samples. I'll enable this feature also for the NLO samples. This issue can remain open until the new Ntuples are available.

**Comment by ktht** [comment]
The NLO signal samples should now have the branches for mHH and cos(theta*).
